version: '3.8'

services:
  db:
    image: postgres
    container_name: quiz-craft-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    image: quiz-craft-api:latest
    container_name: quiz-craft-api
    restart: always
    environment:
      ConnectionStrings__QuizAPIConnectionString: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=PG278748pg"
    ports:
      - 5000:80
    depends_on:
      - db