// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizCraft.Persistence;

#nullable disable

namespace QuizCraft.Persistence.Migrations
{
    [DbContext(typeof(QuizCraftContext))]
    partial class QuizCraftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizCraft.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Categories_Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Categories_Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quizzes Related to C# Programming",
                            Name = "C# Programming"
                        });
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.FillInBlankQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("WordPosition")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_FillInBlankQuestions_Id");

                    b.ToTable("FillInBlankQuestions");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.MultipleOptionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_MultipleOptionQuestions_Id");

                    b.ToTable("MultipleOptionQuestions");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MultipleOptionQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_Options_Id");

                    b.HasIndex("MultipleOptionQuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("PlacementOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Questions_Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Quizzes_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QuizId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 14, 21, 3, 41, 341, DateTimeKind.Utc).AddTicks(7687),
                            CreatedByUserId = 1,
                            Description = "This Quiz contains basic questions about C#.",
                            Title = "C# Fundamentals"
                        });
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_Users_Id");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin"
                        });
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Option", b =>
                {
                    b.HasOne("QuizCraft.Models.Entities.MultipleOptionQuestion", "MultipleOptionQuestion")
                        .WithMany("Options")
                        .HasForeignKey("MultipleOptionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Options_MultipleOptionQuestionId_MultipleOptionQuestions_Id");

                    b.Navigation("MultipleOptionQuestion");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Question", b =>
                {
                    b.HasOne("QuizCraft.Models.Entities.FillInBlankQuestion", "FillInBlankQuestion")
                        .WithOne("Question")
                        .HasForeignKey("QuizCraft.Models.Entities.Question", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FillInBlankQuestions_QuestionId_Questions_Id");

                    b.HasOne("QuizCraft.Models.Entities.MultipleOptionQuestion", "MultipleOptionQuestion")
                        .WithOne("Question")
                        .HasForeignKey("QuizCraft.Models.Entities.Question", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MultipleOptionQuestions_QuestionId_Questions_Id");

                    b.HasOne("QuizCraft.Models.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_QuizId_Quizzes_Id");

                    b.Navigation("FillInBlankQuestion");

                    b.Navigation("MultipleOptionQuestion");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Quiz", b =>
                {
                    b.HasOne("QuizCraft.Models.Entities.Category", null)
                        .WithMany("Quizzes")
                        .HasForeignKey("CategoryId");

                    b.HasOne("QuizCraft.Models.Entities.User", "CreatedByUser")
                        .WithMany("QuizzesCreatedBy")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Quizzes_CreatedByUserId_Users_Id");

                    b.HasOne("QuizCraft.Models.Entities.Quiz", null)
                        .WithMany("Categories")
                        .HasForeignKey("QuizId");

                    b.HasOne("QuizCraft.Models.Entities.User", "UpdatedByUser")
                        .WithMany("QuizzesUpdatedBy")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_Quizzes_UpdatedByUserId_Users_Id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Category", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.FillInBlankQuestion", b =>
                {
                    b.Navigation("Question")
                        .IsRequired();
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.MultipleOptionQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Question")
                        .IsRequired();
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.Quiz", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizCraft.Models.Entities.User", b =>
                {
                    b.Navigation("QuizzesCreatedBy");

                    b.Navigation("QuizzesUpdatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
