# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - quiz-craft-api

env:
  AZURE_WEBAPP_NAME: quiz-craft-api  

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.AzureAppService_ContainerUsername_a7c7da46fa374c2dad471477e7df4475 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_af5dfd855fb54bc899c8432d914f959b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_a7c7da46fa374c2dad471477e7df4475 }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
        build-args: |
                ASPNETCORE_ENVIRONMENT=Production
                ConnectionStrings__QuizAPIConnectionString=${{ secrets.QUIZ_DB_CONNECTION_STRING }}
                ExternalServices__OpenAPIKey=${{ secrets.OPEN_API_KEY }}
                SecurityToken=${{ secrets.SECURITY_TOKEN }}
                ConnectionStrings__ApplicationInsights=${{ secrets.APP_INSIGHTS }}
        context: .
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.AZURE_WEBAPP_NAME }}'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f844c24975e49e583ecf1c94c412769 }}
        images: '${{ secrets.AzureAppService_ContainerUsername_a7c7da46fa374c2dad471477e7df4475 }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}'